### ISSUE TITLE
Saving nodes without image on image field when cardinality is set to 1 causes an error

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#384] opened 2018-08-21 17:24 UTC
On Umami installation profile the article node type has image field with cardinality set to allow uploading single image. If a user doesn't upload an image to that field and tries to save a node, it causes the following error:
![screen shot 2018-08-22 at 00 17 37](https://user-images.githubusercontent.com/1845495/44417916-22628600-a5a1-11e8-8082-fd1ac2b2e8de.png)

The field is not configured to be required so that shouldn't be the cause for the problem.

Here's a gif to help to reproduce the problem:
![image_upload_empty_error](https://user-images.githubusercontent.com/1845495/44418129-c2b8aa80-a5a1-11e8-8d22-f39763aa1d2b.gif)

**Comment by dawehner** [comment] 2018-08-24 14:25
I think this is a duplicate of https://github.com/jsdrupal/drupal-admin-ui/issues/395 isn't it?

**Comment by lauriii** [comment] 2018-08-24 14:57
No, this is not duplicate for that. This bug is separate.

**Comment by dawehner** [comment] 2018-08-24 15:03
Oh I see, one is for attributes and one is for relationships?

**Closed** 2018-08-28 21:14 UTC
Labels: Bug 🐛
