### ISSUE TITLE
Installation fail.

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui#532] opened 2018-11-06 18:28 UTC
I have just cleared away my drupal-admin-ui  directory structure and am having trouble reinstalling

after  composer clear-cache

I follow the readme  with this command and here is the resulting error messages.

```
composer create-project jsdrupal/drupal-admin-ui-demo -s dev --prefer-dist
Installing jsdrupal/drupal-admin-ui-demo (dev-master 3b7f86cb78e2d86af1ffb165938397e550c1feff)
  - Installing jsdrupal/drupal-admin-ui-demo (dev-master 3b7f86c): Downloading (100%)         
Created project in /Users/martin/sites/drupal-admin-ui-demo
Could not scan for classes inside "docroot/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "docroot/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
Gathering patches for root package.
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

                                                                                                                   
  [RuntimeException]                                                                                               
  Could not scan for classes inside "docroot/core/lib/Drupal.php" which does not appear to be a file nor a folder  
                                                                                                                   

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by martinfrances107** [comment] 2018-11-07 14:14
Just looking at this.... in the cold light of day.

I can make progress here if I : -

rm composer.lock
composer setup

Then I get these error messages 

effectively saying that patches in drupal/schema are out of sync.

```
 - Applying patches for drupal/schemata
    https://www.drupal.org/files/issues/2018-04-28/2967572--schemata--multiple-minor-adjustments--3.patch (Small inaccuracies for JSON API schemas)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-04-28/2967572--schemata--multiple-minor-adjustments--3.patch
    https://www.drupal.org/files/issues/2018-07-20/2987199-2.patch (Take the field label into account for entity references)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-07-20/2987199-2.patch
    https://www.drupal.org/files/issues/2018-08-30/promote_returning_boolean_value_instead_of_integer-2996099-2.patch (Returning boolean type for promote to homepage)
```

**Comment by maverickdude** [comment] 2018-11-08 14:00
I'm getting the same error while installation.

**Comment by martinfrances107** [comment] 2018-11-16 12:56
@justafish, @dawehner 

Thank you both ... it is good to see some of the patching going away.

While the package managers are still on old broken code. I can confirm that the recent-ish merges have fixed the issue.

**Comment by maverickdude** [comment] 2018-11-23 12:41
@martinfrances107 
Glad to know that installation is working for you. But it's still failing for me.

**Comment by martinfrances107** [comment] 2018-11-24 12:52
I think I have man-handled the code until it works ... and fooled myself into thinking this could be closed.

I tried again just not and observed this...

Instead of composer create-project ... I was doing the equivalent

which is 

git clone ..
and then composer install

I think it got it to work by deleting composer.lock and forcing a composer update to latest as opposed to update to version numbers specified by those in the lock file.

**Comment by martinfrances107** [comment] 2018-11-28 14:44
I spend a little time looking at this... no solution yet. but I fell more informed

I am on composer 1.7.3 and I suspect a versioning bump is causing the break. and why deleting the composer.lock is a hacky solution.

https://github.com/composer/composer/blob/master/CHANGELOG.md

>Fixed create-project not checking the checking the latest commit out when a cache was already present

The runtime error 

> Could not scan for classes inside "docroot/core/lib/Drupal.php" .....

can be repeated by running  

composer dumpautoload

so it looks like composer is running that "autoload" optimisation before we have pull in and built drupal and all is sub dirs.

If someone with a working installation process could report what composer version they are on ... that would be useful.

**Comment by martinfrances107** [comment] 2018-11-29 19:55
just making notes for myself laur_iii reports installation fails with composer versions  1.7.0 and 1.7.3
So what I said above about composer versioning is just wrong.

**Comment by miiimooo** [comment] 2018-11-30 08:33
Just for someone who comes here for the first time and tries to install and fails with the "Could not scan.." error. I did:

```
git clone
cd demo/
composer install
composer setup
composer start
```
... and wow!

**Comment by martinfrances107** [comment] 2018-12-01 13:05
Regarding this error

> Unable to install modules: module 'admin_ui_support' is missing its dependency module openapi.

Just outlining the solution, in short 

The admin_ui_support module has a dependency .. and due to a new-ish policy we need as associated module composer.json file

here is the relevant quote from 

https://www.drupal.org/docs/8/creating-custom-modules/add-a-composerjson-file

> If a module does not have any dependencies, or the dependencies are solely other drupal modules, then a composer.json is **not required**

As usual the explanation is bigger than the fix.

**Comment by martinfrances107** [comment] 2018-12-04 19:30
I am shutting down the "correct openAPI dependencies" PR - before I do that, I am posting lauriii's comments here as it is a useful in the search - tracking down why the openAPI is not being picked up. 

According to the documentation the format is following:
https://www.drupal.org/docs/8/creating-custom-modules/let-drupal-8-know-about-your-module-with-an-infoyml-file

dependencies - A list of other modules your module depends on. Dependencies should be namespaced in the format {project}:{module}, where {project} is the project name as it appears in the Drupal.org URL (e.g. drupal.org/project/views) and {module} is the module's machine name. Dependencies can also include version restrictions, for examplewebform:webform (>=8.x-5.x). Note that if your module has dependencies on other contributed modules or libraries, these should be declared in the module's composer.json file.

**Comment by martinfrances107** [comment] 2018-12-05 11:05
Sorry if this is coming out in stop and starts

Just posting a workaround which works for me -- by inserting 2 steps between b and c.

a) composer create-project jsdrupal/drupal-admin-ui-demo -s dev --prefer-dist
b) cd drupal-admin-ui-demo
(fix1) rm vendor/composer/installed.json 
(fix2) composer install
c) composer setup

The next problem I have is with a later step 

composer devify

the copy command fails as .env is now longer in the expected directory.
[ since the workspace patch was developed ] 

this is clearly broken I am generating a PR for this now.

**Comment by mattgrill** [comment] 2018-12-10 15:35
@martinfrances107 Does this get fixed with #577 being merged?

**Comment by martinfrances107** [comment] 2018-12-10 16:09
No, I tried it this morning ... I think the merge was a step in the right direction.

My workaround listed above .. is still needed and works.

**Comment by lauriii** [comment] 2018-12-10 16:58
I'm wondering if this is could be because the vendor files have been already committed so they don't get removed? Maybe we should manually confirm this isn't the reason for the PR not solving the problem.

**Comment by lauriii** [comment] 2018-12-12 06:34
Update: @mattgrill made a manual commit to the demo repository because I suspected the problem to be that the added files didn't get deleted as part of the build process. Installation should now work, but we should keep this open till we have confirmed that the files don't get added back with the build steps.

**Comment by dawehner** [comment] 2018-12-12 16:11
Nice1

**Comment by martinfrances107** [comment] 2018-12-12 23:18
I tried this a few minutes ago and it works for me... thank you all. 

@maverickdude is that what you see?

**Comment by DizzleMcShizzle** [comment] 2018-12-13 20:44
+1 Works for me!

**Comment by martinfrances107** [comment] 2018-12-14 14:00
@DizzleMcShizzle 

Thanks for the confirmation.... I closed this issue once before prematurely.  So I will be respond appropriate if anyone asks me to reopen it again.

**Comment by lauriii** [comment] 2018-12-20 10:31
Installation is broken again because of there's still something wrong with the CI steps. See https://github.com/jsdrupal/drupal-admin-ui-demo/commit/606291478af4c9291708c71189a8003675831583

**Comment by martinfrances107** [comment] 2018-12-21 13:37
In the meantime there has been a bunch of permissions related fixes merged.

I cannot reproduce the fail...

If you could retry and describe the failure  .. I will help out where I can

**Comment by Insasse** [comment] 2019-01-04 15:00
The installation manual given in the README.md for https://github.com/jsdrupal/drupal-admin-ui-demo isnt correct
What I've done instead was ->
git clone https://github.com/jsdrupal/drupal-admin-ui-demo
rm -rf docroot/*
rm -rf vendor
rm composer.lock
composer install (umami patch fails)
composer setup (fails)

**Closed** 2019-04-12 16:52 UTC
