### ISSUE TITLE
Consider using Typescript

### ISSUE THREAD

**Issue by pixelmord** [jsdrupal/drupal-admin-ui#64] opened 2018-03-31 12:00 UTC
I do not want to open up a huge discussion on pros and cons, but I thought to bring this up early would make sense.
I personally am doing my first project that will go into production with Typescript and saw a definite improvement in code quality and safety. It was hard in the beginning especially with some more complex definitions in React for interfaces of some HOCs of e.g. react-apollo, but in the end, it really pays off especially when an application gets more and more complex.
Since this here will no doubt be a complex beast, I would recommend using Typescript over just defining PropTypes...

I would gladly help by refactoring the current code with https://www.npmjs.com/package/react-scripts-ts if we can agree upon using TS

**Comment by justafish** [comment] 2018-03-31 12:48
Thanks for bringing this up! Whilst I think TypeScript (and Flow) are great. The thing that makes me hesitate the most is this:
https://insights.stackoverflow.com/survey/2018#technology
JavaScript is at 70% and TypeScript at 17%
I think we're already attempting to make a big leap for the Drupal community in technology terms, this might be a bit too much (for now). One of the biggest goals for me is making this comfortable and accessible to "regular" JavaScript developers.

It's nice to see it's one of the most loved languages though! https://insights.stackoverflow.com/survey/2018#technology-most-loved-dreaded-and-wanted-loved

**Comment by dawehner** [comment] 2018-03-31 12:56
We had a similar discussion for a new project we had a work. One thing we realized tools like typescript or flow exist as people experienced pain along the path and came up with a solution for it. 

This actually really similar to how redux for example came in place. People realized that local state managment can be hard, so they came up with the [flux architecture](http://fluxxor.com/what-is-flux.html). Then they saw the problem of having multiple stores laying around, looked around and figure out there is this nice architecture and implemented it in redux.

I think we as the full Drupal community should experience the same path for typesystems like typescript/flow. While I totally agree that they totally add huge amount of value on custom projects, I think the overall Drupal community isn't there to really use this tools. Without the experience over time, which custom projects have too, it is less obvious what these tools over. 
When we do though experience the path, it might become clear whether typescript of flow is the better tool for us. Once we are there then, we can actually use it properly, which means for example using https://flow.org/en/docs/types/unions/ as much as possible for example.

**Comment by rsanzante** [comment] 2018-07-04 12:45
I would like to add some thoughts to this conversation:

- While JS is very popular and TypeScript is not so popular, Angular is the second popular library/framework/tool, and Angular uses TypeScript.

- TypeScript learning curve is very very easy. It's just JavaScript with many other things from classic OOP, pretty straightforward. See https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html. The handbook (https://www.typescriptlang.org/docs/handbook/basic-types.html) is short.

- The toolset can handle all the transpile and packing processes seamlessly.

- TypeScript is a superset of JavaScript. Any JavaScript code runs in a TypeScript script.

- JavaScript is a powerful language but so flexible that it's easy to shoot yourself in the foot. Few are the braves that totally understand JavaScript, and books like this one are a proof of this claim: https://github.com/getify/You-Dont-Know-JS (You Don't Know JavaScript). 

- For a complex project, JavaScript is hard to debug, hard to refactor and even hard to read when all its advanced capabilities are used. 

- For small to medium components I think it's ok to use plain JavaSript, for medium to big complex applications like a Drupal Admin UI I think plain JavaScript is a risk.

**Comment by martinfrances107** [comment] 2018-07-09 12:52
I would like to make the case for Typescript or at least turning on flow ...

In order that we can, in the long term,  solve one glaring obvious problem...

The project is at a early stage but ...
I have been caught out on this a few times .. it is sometimes really good to be able to say that **something** between week 15-20 destroyed our performance and XYZ  is this why we need to insert costly redesign. it is just better to suffer redesign earlier rather than later.

So I have been looking at our future prospects of getting a 100% on Chrome's lighthouse performance tests and the glaringly obvious problem is we suck at the "time to first meaningful paint" test.  As is common for javascript apps -  initial building the AST tree, parsing javascript and then initial rendering  is the bottleneck. ( Hence code splitting, and the motivation for loading screens and application shells) 

Here is a summary of  this video about web assembley

https://www.youtube.com/watch?v=pBYqen3B2gc

From  2019  garbage collection may appear in Web assembly. At which point React apps can set their build targets to be WASM. WASM is by design a streamable format .... as as soon a the first byte arrives then previously blocking ingestion tasks can start... or in the case of building the AST tree it is simply no longer required. [ It is funny that the analysis for large applications in  C++ and java is that the expected gain in execution performance is a tiny 20-30%!!!  but the time to first paint will be revolutionary ] 

At the end of the youtube videos comes my point, sorry for the long winded diatribe. 

Adding  type checking, which  typescript does so well ... aids in the trans-piling of javascript to web assembly.

So speaking in positive steps I am going to convert a small section of our code base to type script -- and see where we go from there.

**Comment by martinfrances107** [comment] 2018-07-09 14:08
Just relaying the outcome of a slack conversation with @justafish 

> it's highly unlikely it'll be accepted into the project at this point in time.

No problem really ... it is a polarising subject... and there are plenty of ways of making an app fast.

**Comment by dawehner** [comment] 2018-07-10 17:15
I created an issue where we can collect problems where TS/flow would have helped: https://github.com/jsdrupal/drupal-admin-ui/issues/190

**Comment by justafish** [comment] 2018-10-22 17:06
CRA 2.0, which we've now upgraded to, supports TypeScript! We discussed this during the #javascript meeting today and myself, @lauriii, and @martinfrances107 were in favour of moving to using it.
I think a good start would be a PR to enable this support and convert one of the simpler components.
https://github.com/facebook/create-react-app/blob/master/docusaurus/docs/adding-typescript.md

**Comment by martinfrances107** [comment] 2018-10-23 06:18
> I think a good start would be a PR to enable this support

I am playing around with this in the background 

just making notes about the conversion 

> You can no longer import React from 'react';. React is exported as a CommonJS module which does not use a default export.

so we must start using this code pattern 

import * as React from 'react';
import * as ReactDOM from 'react-dom';

https://levelup.gitconnected.com/typescript-and-react-using-create-react-app-a-step-by-step-guide-to-setting-up-your-first-app-6deda70843a4

**Comment by martinfrances107** [comment] 2018-10-23 09:50
There are ways of doing it today, but yes I think that to wait a little maybe the better option.

Just to discuss what the conversion may involve

https://medium.com/@amcdnl/react-typescript-%EF%B8%8F-647aa7d054a9

There are for example perl scripts, cobbled together online which can be used to automate the adjustment of say for example the import changes I talked about earlier.



```
FILENAME=$1
react-js-to-ts $FILENAME
TS_FILENAME=${FILENAME/\.js/\.tsx}
perl -0777 -p -i -e 's/(?<=[^\n]\n)((type|let|var|const|class|function|interface|export( default)?) \w+|  (static )?\w+( =|\((\w+|\))))/\n$1/g' $TS_FILENAME
perl -0777 -p -i -e 's/(\n  \w+) = (?:(?<args>\w+)|\((?<args>\w+(?:, \w+)*)\)|\(\)) => {/$1($+{args}) {/g' $TS_FILENAME
perl -0777 -p -i -e "s/import React, { (Pure)?Component(, Fragment)? } from 'react';/import * as React from 'react';/g" $TS_FILENAME
perl -0777 -p -i -e 's/extends ((Pure)?Component)/extends React.$1/g' $TS_FILENAME
perl -0777 -p -i -e 's/<(\/)?Fragment/<$1React.Fragment/g' $TS_FILENAME
```

**Comment by martinfrances107** [comment] 2018-10-25 08:53
Just playing around with this in the background....

Looking at app.jsx and the error messages that occur when I convert into app.tsx ( typescript )

appending of the "option" object to the "jss" object after creation triggers errors

This code snippet from https://material-ui.com/customization/css-in-js/
shows the conversion

```
const jss = create({
  ...jssPreset(),
  // We define a custom insertion point that JSS will look for injecting the styles in the DOM.
  insertionPoint: 'jss-insertion-point',
});
```

**Comment by martinfrances107** [comment] 2018-10-25 12:02
Just documenting a issue 

We are going to have to do this, as some packages have not yet completed the typescript definitions.

```
// @ts-ignore
storiesOf('FileUpload', module).addWithJSX(..)
```

here is the addon-jsx module pending issue.

https://github.com/storybooks/addon-jsx/issues/36

**Comment by martinfrances107** [comment] 2018-10-26 16:37
So this is a architecture comment 

There are no plans within react-rte to provide a typescript types file :)

https://github.com/sstur/react-rte/issues/105

I am close to finishing a first cut of the typescript conversion ....just for giggles here are the npm packages pulled into devDependencies so far.

Most of our external modules are well supported 
 ```
   "@types/enzyme": "^3.1.14",
    "@types/jest": "^23.3.7",
    "@types/jss": "^9.5.7",
    "@types/qs": "^6.5.1",
    "@types/react": "^16.4.18",
    "@types/react-dom": "^16.0.9",
    "@types/react-jss": "^8.6.0",
    "@types/react-redux": "^6.0.9",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-router-redux": "^5.0.16",
    "@types/react-side-effect": "^1.1.1",
    "@types/storybook__addon-actions": "^3.4.1",
    "@types/storybook__addon-knobs": "^3.4.1",
    "@types/storybook__react": "^3.0.9",
```

**Comment by martinfrances107** [comment] 2018-10-27 19:38
Sorry for the distraction 

What I said above about a lack of typescript package for react-tre

also applied to interweave.. so AddContent.tsx will get this change

+// @ts-ignore
 import { Markup } from 'interweave';

**Comment by martinfrances107** [comment] 2018-11-03 23:13
So my first rough cut typescript branch is showing signs of life.

I wanted a rough cut where all the files are converted at once ...just so all the function parameter definitions and new interfaces  interlock and start to hang together as a whole.

Later I can start to ask architectural questions with a view to moving and refining all the interfaces I have defined. The mega patch is unreviewable so I plan to makes a series of smaller targeted pull requests.

When  dawehner said above that maybe we should wait and 

> Maybe I'm missing something though.

I am going to  describe that missing something .. and ask for help

I am getting this runtime error related to deepmarge  and this error message from the npm documentation.

> merge is not a function, add this alias to your Webpack config:......

https://www.npmjs.com/package/deepmerge

There is a known bug and a known work around.

but it involves modifying the webpack config ... So finally my question 

Is that possible in the context of create-react app? I could not see in the documentation on how to modify the config?

**Comment by dawehner** [comment] 2018-11-23 00:00
I think it is fine to close this issue now :)

**Closed by dawehner** 2018-11-23 00:00 UTC
